@startuml
!pragma teoz true
actor Alice
actor Bob
Alice -> Alice: Generates long-term key pair
activate Alice
& Bob -> Bob: Generates long-term key pair
activate Bob
Alice -> Alice: Initiate a key exchange,\ngenerating its ephemeral key pair.
activate Alice
Alice -> Bob: Send ""packet1""
Bob -> Bob: Processes ""packet1"" from Alice,\ngenerating its ephemeral key pair
activate Bob
Bob -> Alice: Send ""packet2""
Alice -> Alice: Processes ""packet2"" from Bob,\nand computes its copy of the\nsession keys
activate Alice
Alice -> Bob: Send ""packet3""
Bob -> Bob: Processes ""packet3"" from Alice,\nand computes its copy of the\nsession keys
activate Bob
@enduml